// demo-apps/demoapp003-nextjs-bff/app/applications/[id]/decline-notice/page.tsx
import type { Metadata } from 'next';
import Link from 'next/link';
import { connection } from 'next/server';

import { api, codeOf, type DeclineNotice } from '@/lib/api';
import { ErrorMarker } from '@/lib/outcome';

export const metadata: Metadata = { title: 'Decline notice — Loan origination' };

/** Customer-facing text only (spec §9): no rule IDs, thresholds or scores. */
export default async function DeclineNoticePage({ params }: { params: Promise<{ id: string }> }) {
    await connection();
    const { id } = await params;
    let notice: DeclineNotice | null = null;
    let error: string | null = null;
    try {
        notice = await api.declineNotice(id);
    } catch (e) {
        error = codeOf(e);
    }
    return (
        <>
            <h1>Decline notice</h1>
            <p>
                <Link href={`/applications/${id}`}>Back to application</Link>
            </p>
            {notice && (
                <>
                    <h2>Why we could not approve this application</h2>
                    <ul>
                        {notice.reasons.map((r) => (
                            <li key={r.code} data-testid="decline-reason" data-code={r.code}>
                                {r.text}
                            </li>
                        ))}
                    </ul>
                    <p data-testid="agency" data-value={notice.creditReferenceAgencyName ?? ''}>
                        {notice.creditReferenceAgencyDisclosed
                            ? `We used information from ${notice.creditReferenceAgencyName}.`
                            : 'No credit reference agency information decided this outcome.'}
                    </p>
                    <p data-testid="human-review-offer" data-value={String(notice.humanReviewAvailable)}>
                        {notice.humanReviewAvailable
                            ? 'You can ask for a person to review this decision within 30 days.'
                            : 'This decision was made by a person.'}
                    </p>
                </>
            )}
            {error && <ErrorMarker code={error} />}
        </>
    );
}

// demo-apps/demoapp002-angular-spa/src/app/pages/decline-notice.ts
import { Component, effect, inject, input, signal } from '@angular/core';
import { RouterLink } from '@angular/router';

import { Api, ApiError, type DeclineNotice } from '../api';
import { reasonText } from '../format';

/** Customer-facing text only (spec §9): no rule IDs, thresholds or scores. */
@Component({
    selector: 'lop-decline-notice',
    imports: [RouterLink],
    template: `
        <h1>Decline notice</h1>
        <p><a [routerLink]="['/applications', id()]">Back to application</a></p>
        @if (notice(); as n) {
            <h2>Why we could not approve this application</h2>
            <ul>
                @for (r of n.reasons; track r.code) {
                    <li data-testid="decline-reason" [attr.data-code]="r.code">{{ r.text }}</li>
                }
            </ul>
            <p data-testid="agency" [attr.data-value]="n.creditReferenceAgencyName ?? ''">
                @if (n.creditReferenceAgencyDisclosed) {
                    We used information from {{ n.creditReferenceAgencyName }}.
                } @else {
                    No credit reference agency information decided this outcome.
                }
            </p>
            <p data-testid="human-review-offer" [attr.data-value]="n.humanReviewAvailable">
                @if (n.humanReviewAvailable) {
                    You can ask for a person to review this decision within 30 days.
                } @else {
                    This decision was made by a person.
                }
            </p>
        }
        @if (error(); as code) {
            <p role="alert" class="error" data-testid="error" [attr.data-reason]="code">{{ text(code) }}</p>
        }
    `,
})
export class DeclineNoticePage {
    private readonly api = inject(Api);
    readonly id = input.required<string>();
    readonly notice = signal<DeclineNotice | null>(null);
    readonly error = signal<string | null>(null);
    readonly text = reasonText;

    constructor() {
        effect(() => {
            this.api.declineNotice(this.id()).then(
                (n) => this.notice.set(n),
                (e: unknown) => this.error.set(e instanceof ApiError ? e.code : 'UNEXPECTED_ERROR'),
            );
        });
    }
}
